# Generated by Django 5.2.1 on 2025-05-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Damaged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Damaged',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price', models.BigIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('type_of_damage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_damaged', to='damaged.type_damaged')),
            ],
        ),
    ]
