# Generated by Django 5.2.1 on 2025-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damaged', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_damaged',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
