# Generated by Django 5.2.1 on 2025-05-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Checked',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Checked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('product_code', models.BigIntegerField()),
                ('quantity_real', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_system', models.DecimalField(decimal_places=3, max_digits=10)),
                ('difference', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inventory_checked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory_checked')),
            ],
        ),
    ]
