# Generated by Django 5.2.1 on 2025-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Shelflife',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shelflife', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
